import { AbilityCard } from '../ability-cards';

export const combatCards: AbilityCard[] = [
	{
		id: 'aimed-shot',
		title: 'Aimed Shot',
		primaryType: 'combat',
		rarity: 1,
		cost: 1,
		encounterValue: 2,
	},
	{
		id: 'observe-tactics',
		title: 'Observe Tactics',
		primaryType: 'combat',
		rarity: 1,
		cost: 1,
		encounterValue: -1,
		encounterText: '+2 Combat Skill Points',
	},
	{
		id: 'charge',
		title: 'Charge',
		primaryType: 'combat',
		rarity: 1,
		cost: 2,
		encounterValue: 1,
		consumable: true,
		consumeText: 'Movement +2',
	},
	{
		id: 'improvised-weapon',
		title: 'Improvised Weapon',
		primaryType: 'combat',
		rarity: 1,
		cost: 2,
		encounterValue: 3,
		encounterText: 'Encounter Value is reduced by 2 each time it is used.',
	},
	{
		id: 'mag-dump',
		title: 'Mag Dump',
		primaryType: 'combat',
		rarity: 1,
		cost: 1,
		encounterValue: 4,
		encounterText: 'Cannot be played with any other Combat Type cards.',
	},
	{
		id: 'suppression',
		title: 'Suppression',
		primaryType: 'combat',
		rarity: 1,
		cost: 2,
		encounterValue: 1,
		encounterText: 'If total encounter value is within 4 of required value, ignore any negative health effects from the encounter card.',
	},
	{
		id: 'momentum',
		title: 'Momentum',
		primaryType: 'combat',
		rarity: 2,
		cost: 2,
		encounterValue: 0,
		encounterText: '+1 Encounter Value for each other card played in this enounter. Creates a copy of itself '
	},
	{
		id: 'flamethrower',
		title: 'Flamethrower',
		primaryType: 'combat',
		rarity: 2,
		cost: 2,
		encounterValue: 2,
		tags: ['Fire'],
	},
	{
		id: 'improvised-explosive',
		title: 'Improvised Explosive',
		primaryType: 'combat',
		rarity: 2,
		cost: 2,
		encounterValue: 5,
		encounterText: 'You must discard 1 ability card in order to play this.',
	},
	{
		id: 'grenade',
		title: 'Grenade',
		primaryType: 'combat',
		rarity: 2,
		cost: 2,
		encounterValue: 6,
		encounterText: 'Alert Level +1.',
	},
	{
		id: 'berserk',
		title: 'Berserk',
		primaryType: 'combat',
		rarity: 3,
		cost: 1,
		encounterValue: 5,
		encounterText: 'Health -1.',
	},
	{
		id: 'tend-wounds',
		title: 'Tend Wounds',
		primaryType: 'combat',
		rarity: 3,
		cost: 2,
		encounterValue: -2,
		encounterText: 'Health +3.',
	},
	{
		id: 'departing-gift',
		title: 'Departing Gift',
		primaryType: 'combat',
		rarity: 3,
		cost: 3,
		encounterValue: 10,
		encounterText: 'You must destroy 1 ability card in order to play this.',
	},
];
