import { AbilityCard, AbilityCardId } from '../ability-cards';

export const stealthCards: AbilityCard[] = [
	{
		id: AbilityCardId.SNEAK,
		title: 'Sneak',
		primaryType: 'stealth',
		rarity: 1,
		cost: 1,
		encounterValue: 2,
	},
	{
		id: AbilityCardId.HIDDEN_BLADE,
		title: 'Hidden Blade',
		primaryType: 'stealth',
		secondaryTypes: ['combat'],
		rarity: 1,
		cost: 2,
		encounterValue: 2,
	},
	{
		id: AbilityCardId.TIPTOE,
		title: 'Tiptoe',
		primaryType: 'stealth',
		rarity: 1,
		cost: 2,
		encounterValue: 1,
		successText: 'Alert Level -1'
	},
	{
		id: AbilityCardId.HIDE,
		title: 'Hide',
		primaryType: 'stealth',
		rarity: 1,
		cost: 1,
		encounterValue: 0,
		consumable: true,
		consumeText: 'Deactivate an encounter. +1 Stealth Skill Point. Can only be used if Stealth is strong for the Encounter.'
	},
	{
		id: AbilityCardId.PICKPOCKET,
		title: 'Pickpocket',
		primaryType: 'stealth',
		rarity: 1,
		cost: 2,
		encounterValue: -1,
		successText: '+1 Credit'
	},
	{
		id: AbilityCardId.STASH,
		title: 'Stash',
		primaryType: 'stealth',
		rarity: 2,
		cost: 7,
		encounterValue: 1,
		consumable: true,
		consumeText: '+5 Stealth Points'
	},
	{
		id: AbilityCardId.SILENCER,
		title: 'Silencer',
		primaryType: 'stealth',
		rarity: 2,
		cost: 2,
		encounterValue: 0,
		encounterText: 'Negates negative alert level effects.',
	},
	{
		id: AbilityCardId.LIGHTFOOTED,
		title: 'Light Footed',
		primaryType: 'stealth',
		rarity: 2,
		cost: 1,
		encounterValue: 4,
		encounterText: '-1 Encounter Value for each equipment carried',
	},
	{
		id: AbilityCardId.DECOY,
		title: 'Decoy',
		primaryType: 'stealth',
		rarity: 2,
		cost: 2,
		encounterValue: 2,
		consumable: true,
		consumeText: 'Deactivate an encounter. Move to an adjacent square.'
	},
	{
		id: AbilityCardId.RECON,
		title: 'Recon',
		primaryType: 'stealth',
		rarity: 3,
		cost: 2,
		encounterValue: 2,
		consumable: true,
		consumeText: 'Reveal all squares within 4 spaces.',
	},
	{
		id: AbilityCardId.ASSASSINATE,
		title: 'Assassinate',
		primaryType: 'stealth',
		rarity: 3,
		cost: 4,
		encounterValue: 15,
		destroys: true,
	},
];